### ISSUE TITLE
Just checking this out... 

### ISSUE THREAD

**Issue by XeonG** [richardbiely/Voxelmetric#19]
Good to see voxelmetric has been picked up again, your enhancements to the original in performance is much better and its good to see this project has an active developer for it, I was planning to use original voxelmetric but progress on the base engine slowed to a halt.

Obviously its still in alpha.. but I see the enhancements you have planned still so I am looking forward to seeing those. 

I think adding some basic worldedit type tools, and getting it working in editor scene view would help a lot for game makers to make worlds/levels without needing to be good at writing procedural terrain generation.. its something i've never been able to do well, and think the time invested in coding is better spent on gameplay and tools for me, unless someone would like to help with doing tutorials on voxelmetric with terrain generation stuff.

Some questions
-the block breaking is broken on things like wildgrass, 3d objects etc..i mean its not detected as block when you try to place other blocks on it, can you point me to the code that needs adjusting to fix this... ie for breaking it, placing solid blocks on top of things like leaves/wildgrass isn't needed.. pretty sure I had found it months ago  but its all so new again now :)

-I believe adding colliders support is in the enhancements, when it is added can you do an example scene with ai/pathfinding working?

-voxel patches re https://github.com/Voxelmetric/Voxelmetric/issues/55

it was kinda got supported ie multiple worlds but the original author didn't have time for it, do you think you will support it?  it was something that interested me

**Comment by richardbiely** [comment]
"I think adding some basic worldedit type tools..."
It is planned :) However, I first want to finish some more basic features and put Voxe's core into a dynamic library. Afterwards, I want users to be able to visualy (inside Unity) modify block properties, configs etc. The changes they make would be then transfered to the respective config files and vice-versa.

"the block breaking is broken..."
It is broken in orignal Voxelmetric alpha as well. However, I'll get this working of course. Later, I even plan to implement a feature that would cause clutter above a destroyed block to disappear as well. And if you e.g. destroy a block under a small enough tree, I want to tree to fall etc.

"-I believe adding colliders support"
I implemented support for colliders today. I still have to prepare a proper demo, though. Until it is ready, I made colliders generate around viewer's position.

"-voxel patches re Voxelmetric#55"
I want to make it work.

**Comment by XeonG** [comment]
thats cool then

btw your Jun 25th commits seemed to have made block break/creating slower, like half the speed and not as snappy.. like if you click fast it might not show any block removes, then a whole bunch get removed.. before each time u removed a block the update came through pretty instantly. The ms time in behaviourUpdate went up a bit more aswel... is this because of collider code now?  just seems quiet noticeable now

**Comment by richardbiely** [comment]
I did not notice any slowdowns. However, for the chunks around the viewer, logically, it has to be slower  due to colliders being updated.

I would not mind this much because I already have some optimizations ready and will push them later after I finish more important things (moving Voxe to a dynamic library has priority now).

**Comment by XeonG** [comment]
what is the benefit of moving voxe to a dynamic library?  will the source for it still be available ? and does it create any extra hassle with compiling for different platforms?

**Comment by richardbiely** [comment]
I would say there are just too many benefits. For instance:
1) independece on Unity3D = bigger spread
2) the code can be tuned using a proper profiler, not the excuse of a profiler Unity3D offers

It will still (and always will) remain open-source.
There should be no extra hassle compiling projects for different platforms.
