### ISSUE TITLE
Got these 2 errors for missing namespace

### ISSUE THREAD

**Issue by XeonG** [richardbiely/Voxelmetric#21]
Hi,

Some of your changes seem to be missing ...

`Assets/Voxelmetric/Code/Utilities/ChunkLoaders/LoadChunks.cs(2,31): error CS0234: The type or namespace name`Utilities' does not exist in the namespace `Assets.Voxelmetric.Code'. Are you missing an assembly reference?

Assets/Voxelmetric/Code/Utilities/ChunkLoaders/LoadChunksSimple.cs(2,31): error CS0234: The type or namespace name `Utilities' does not exist in the namespace`Assets.Voxelmetric.Code'. Are you missing an assembly reference?
`

**Comment by richardbiely** [comment]
Try the newest commit. There were some files missing in my previous commits and I did some changes this morning.
I'll take a look at it anyway later this day.

**Comment by richardbiely** [comment]
Yes. Now that I'm looking at it, it was because TimeBudgetHandler.cs was not commited. But that is no longer true.
