### ISSUE TITLE
Another error corrupted worldsave?

### ISSUE THREAD

**Issue by XeonG** [richardbiely/Voxelmetric#26]
Only appears once at start of playback

`Assertion failed. Value was False
Expected: True
UnityEngine.Assertions.Assert:IsTrue(Boolean)
Voxelmetric.Code.Common.Memory.MarshalMemPool:Pop(Int32) (at Assets/Voxelmetric/Code/Common/Memory/MarshalMemPool.cs:38)
Voxelmetric.Code.Common.IO.StructSerialization:DeserializeArray(Byte[], MarshalMemPool) (at Assets/Voxelmetric/Code/Common/IO/StructSerialization.cs:84)
Voxelmetric.Code.Core.Serialization.Save:Debinarize(BinaryReader) (at Assets/Voxelmetric/Code/Core/Serialization/Save.cs:81)
Voxelmetric.Code.Common.IO.FileHelpers:DebinarizeFromFile(String, IBinarizable) (at Assets/Voxelmetric/Code/Common/IO/FileHelpers.cs:128)
Voxelmetric.Code.Core.Serialization.Serialization:Read(Chunk) (at Assets/Voxelmetric/Code/Core/Serialization/Serialization.cs:78)
Voxelmetric.Code.Core.Serialization.Serialization:LoadChunk(Chunk) (at Assets/Voxelmetric/Code/Core/Serialization/Serialization.cs:46)
Voxelmetric.Code.Core.StateManager.ChunkStateManagerClient:OnLoadData(ChunkStateManagerClient) (at Assets/Voxelmetric/Code/Core/StateManager/ChunkStateManagerClient.cs:323)
Voxelmetric.Code.Core.StateManager.ChunkStateManagerClient:<LoadData>m__1C(Object) (at Assets/Voxelmetric/Code/Core/StateManager/ChunkStateManagerClient.cs:350)
Voxelmetric.Code.Common.Threading.TaskPool:ThreadFunc() (at Assets/Voxelmetric/Code/Common/Threading/TaskPool.cs:158)`

**Comment by richardbiely** [comment]
Try to delete your save files just to make sure that it is not an issue of incompatibility with previous revisions.

It it does not help, it's most likely going to be an insuficient size of m_marshaledPool

**Comment by richardbiely** [comment]
Is this still valid or was it an incompatibility/some issue on your end?

**Comment by XeonG** [comment]
It was a worldsave issue, as it went away after deleting the worldsave.. not sure what caused it though.

I did get some other weird crashing and errors which I forgot to save. I've since increased the pool sizes a bit a the size of m_marshaledPool

**Comment by richardbiely** [comment]
Fixed in 8e42517fc221f467f4c73f0ed76de3d1eea89018
