### ISSUE TITLE
IsChunkInViewFrustum.. 

### ISSUE THREAD

**Issue by XeonG** [richardbiely/Voxelmetric#27]
just having it off shaved 2-3ms off per frame, and gained like 100fps

**Comment by XeonG** [comment]
http://i.imgur.com/W3libFX.png

**Comment by XeonG** [comment]
avg is like 4ms on LoadChunksSimple.Update() when idle..  (picture is with deep profile on so ms is out of whack).. but with frustum on, its around 6ms.

**Comment by richardbiely** [comment]
Thanks to these frustum checks, it's possible to generate chunks on-demand (when they first become visible).
If you don't need the feature, turn "Use frustum culling" off on your LoadChunksSimple script.
