### ISSUE TITLE
Colored Blocks Always Green

### ISSUE THREAD

**Issue by ghost** [richardbiely/Voxelmetric#43]
I can't quite wrap my head around the colored blocks demo.

I've looked into the JSON configurations for layers in the "colored" world and it all looks good. This is one of the layer configuration files:
```
{
  "name": "Stone base layer",
  "index": 100,
  "layerType": "AbsoluteLayer",
  "properties": {
    "blockName": "coloredblock",
    "frequency": "32",
    "exponent": "1",
    "minHeight": "40",
    "maxHeight": "56",
    "blockColors": "111,113,116"
  }
}
```
So of course the blockColors property sticks out to me as something that should define the color of the blocks in that layer.

However, when I load the colored world and scene, it's essentially green everywhere, irregardless of the blockColor property defined in a layer's configuration file and how far I dig to attempt to discover other layers.

I know there's no documentation for most of Voxe(lmetric) so I was hoping I could get some pointers as to if the color feature is currently working and something on my end may not be working or if there is a way I can get it working properly, because for this large project I'm not sure where to start, although I'm trying my best to understand at least the terrain generation for now.

Thanks!

**Comment by XeonG** [comment]
I haven't tried it myself in while, but I do know that some bugs have cropped up before in later commits where not everything has been tested. So you could always grab a much older commit from last year and see if it was working then?

Personally wish it were possible to have grey textured blocks where you can define the color both in setup or even later in runtime... dunno if it is possible to use colored blocks mixed in with the textured ones.. not tried it.

**Comment by richardbiely** [comment]
Ever since I started working on this project the colored example has been practically dead. However, I plan to ressurect it soon with some nice features to make it a worthy partner to the textured example.

**Comment by XeonG** [comment]
ooh any hint on the nice features? transparency like colored glass blocks possible?

**Comment by ghost** [comment]
Sounds great! I'm looking forward to any changes. Transparent blocks would be great to be able to define as well.

Just to throw this out there, my friend and I are looking to re-purpose Voxe(lmetric) into a more static world. We don't require or desire world modification, and ideally we don't need to generate extra, unseen layers. I'd like to base our project off of this one primarily because of the performance of V(l). I feel that we could extend various parts of the engine/library to work for cubic objects such as items or characters that require smaller "cube" units.

**Comment by ghost** [comment]
Alright so a little update.

It looks as though if you remove all other layers in that world's config folder (in my case I removed all but the additive dirt noise layer), the color of that layer is set correctly.

What seems to be the issue is that whatever the last layer generated, the faces of all layers become that color. I can see why that may happen during optimization. Don't know exactly where I'd go to fix it though!

**Comment by richardbiely** [comment]
Starting with 2279e786db44fc7bc3749df476a1ccb97fa40f64 colored world should work the way one would expect.

Consider this a placeholder, though. The whole voxel system is currently being reworked to a material based one. After that texture-based or color-based will no longer matter.

**Comment by XeonG** [comment]
that rework sounds great :)
