### ISSUE TITLE
Latest build ...Press [T]

### ISSUE THREAD

**Issue by XeonG** [richardbiely/Voxelmetric#46]
Not sure if you had checked lately.. but is still some problems in the chunk building.. you can see the problems around the chunk borders when using example code you added with hotkey T

`           // Test of ranged block setting
                if (Input.GetKeyDown(KeyCode.T))
                {
                    Code.Voxelmetric.SetBlockRange(world, new Vector3Int(-44, -44, -44), new Vector3Int(44, 44, 44), BlockProvider.AirBlock);
                }`

**Comment by richardbiely** [comment]
Yes, I now. It's because of the optimization involving removal of invisible chunks surrounding the world. It's still not finished. You may have also noticed that some chunk sides that were previously at world's border are rendered even when they should not but when you move, they properly disappear. It's the same issue.

I'm currently working on the new in-memory compression algorithm that is going to be very closely related to geometry generation. This will be fixed when it's finished.

**Comment by XeonG** [comment]
whats the in memory compression algorithm going to achieve?  like I wouldn't say there is any problem with current memory usage right now... at least not at the expensive of cpu cycles on compressing it.. so is it going to be a net benefit this new thing you are working on?

**Comment by richardbiely** [comment]
As with everything in Voxe(lmetric) if you don't feel like using it for some reason you'll be able to turn it off via config.cs.
You might not feel like there is a problem with memory consumption right now but there is. Not to mention I want to be able to display large worlds. Memory compression + LOD are a must for them.

**Comment by XeonG** [comment]
I guess if its for showing larger view distances I'm all for it, but wouldn't the other issue with having growing list of 1500+ chunks checked every frame kind of lower the fps for that or will that be optimized aswel? 

In anycase I look forward to any improvements... I don't know what the roadmap is for whats coming next but if could suggest the block material improvements and built in support for block rotations (I think you already put in base support for that now, which is about as far as i got with it aswel, I never did find where to hook up the changes for the block textures to be appropriately change for block direction)  those things would be preferred to me anyway, because it has more immediate benefit to the featureset of the voxel framework.

**Comment by richardbiely** [comment]
Fixed in: 49895968f245bfb5cf91bca5451e44a2622b0c08
