### ISSUE TITLE
Texture Stretching

### ISSUE THREAD

**Issue by jaspercayne** [richardbiely/Voxelmetric#50]
I'm seeing a lot of rendering issues that looks like all blocks are attempting to take on the properties of connected textures. The textures are being stretched across multiple blocks, and removing or adding blocks adjacent to the blocks displaying incorrect texturing will cause the issue to change based on the new shape of the problematic blocks.

http://imgur.com/a/bmrNc displays the stretching problem fairly well. The block of stone on the top of the structure looks correct, but the ones on the bottom are attempting to share their texture across the long face of the structure. You can see the same issue with the grass and dirt in the background as well.

**Comment by XeonG** [comment]
yeh reported already https://github.com/richardbiely/Voxelmetric/issues/49

needs a custom shader for it -coming soon   i guess..
