### ISSUE TITLE
fyi block side textures rotated incorrectly

### ISSUE THREAD

**Issue by XeonG** [richardbiely/Voxelmetric#51]
![textures](http://i.imgur.com/r1jjIRf.png)

Anyway performance for geometry generation seems much better as of late.. I hope the texturing/custom shader for the stretching issue come soon.. really want to update to the newer commits 👍

**Comment by richardbiely** [comment]
This is no longer true :) Update to a newer revision, please.

**Comment by richardbiely** [comment]
Well, it turned out this is still an issue. It happens just for some corner faces which makes me wonder what it is. I'm reopening the issue until it's fixed.

**Comment by richardbiely** [comment]
I broke it again today in 9064123fc958c4c8341627f4c902aca2a8d359f7

**Comment by richardbiely** [comment]
And there it is - fixed again in: 759b7225013acfa6a604a9b4527b4ab15836fc8d
I just forgot to send face rotation info to the face builder.
