### ISSUE TITLE
some block faces at chunk borders not generated

### ISSUE THREAD

**Issue by XeonG** [richardbiely/Voxelmetric#53]
![Image of Voxelmetric](http://i.imgur.com/TZei5mo.png)

just checking the newer commits seems still a few problems with the geometry, also will you be doing the shader to fix the stretched texture surfaces soon?

**Comment by XeonG** [comment]
just noticed that AO on the chunk borders is also a problem now, including the colored blocks

**Comment by richardbiely** [comment]
> just checking the newer commits seems still a few problems with the geometry

What are your settings? I haven't seen this, yet. It would be best if you sent me your world's save files so that I can reproduce it.

> also will you be doing the shader to fix the stretched texture surfaces soon?

When I get to it. You can set "w" and "h" variables in CubeMeshBuilder.cs to 1 for the time being.

> just noticed that AO on the chunk borders is also a problem now, including the colored blocks

Yes, I know. Will fix that when I get to it. However, once again, don't report multiple issues per ticket please.

**Comment by richardbiely** [comment]
I think I have reproduced it. There's no need to send anything.

**Comment by XeonG** [comment]
The above screenshot was the latest commit (in a new folder), pressed 't' and placed some blocks.. 

so everything default no changes.. was no worldsave 

"You can set "w" and "h" variables in CubeMeshBuilder.cs to 1 for the time being."
oh thanks ...I just tried it but no dice.. are you sure, can you give example?

yeh i'll try keep issues separate in future

**Comment by richardbiely** [comment]
Could you please check whether the issue still persists even after
32e6582101f05aeda35ebb5423e2c26dccdc3e41 ?
There was an issue with synchronizing neighbor blocks after a ranged operation.

**Comment by XeonG** [comment]
yup that seems to be fixed now thanks.
