### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by superfrantv** [richardbiely/Voxelmetric#57]
Hey,

first i'am a non english speaker, i'am from germany.
my project use the original voxelmetric unity project but there are some problems.

If you know about "Stonehearth or CubeWorld" the cubes are only colors, in my project i completet to generate with color codes with only 1 material (in Unity).

The original code is very confusing and there are many things that could be shortened.
Next i want to check out your project to see, which possibles there are.

the second thing is to generate trees because the first code was to generate a chunk from -x to x and -z to z and -y to y, the new code is generate every x-z-point from zero up to maximal. 

i want to generate a world endless in all 6 directions (up/down/right/left..) but it generates only endless right/left/front/back.

Next thing is to use Biomes and generate buildings like trees only with better look.
I would like to adapt the terrain to the building so that it ends flush.

Thank you i hope you understand what i mean.

**Comment by richardbiely** [comment]
Hi,
first off, this project has only very little common with the original Voxelmetric repository. You may find the original confusing but I think it all comes down to how much you understand the codebase. At first glance, everything is confusing :)

Voxe(lmetric) supports the freedom of movement in all 6 axes. This behavior can be controled via Follow Camera X/Y/Z checkboxes on your "Load Chunks Simple" component which is attached to "Main Camera" by default.
Artifical limits to min/max height can be enforced via "minY" and "maxY" parameters of your world's config.
