### ISSUE TITLE
Can't add a player controller.

### ISSUE THREAD

**Issue by llDunno** [richardbiely/Voxelmetric#58]
I've been trying to add a player controller with a model and I only ever end up with it skating around or even falling through the world. I'm new to unity so let me know what info you need.

**Comment by richardbiely** [comment]
Hi,
for questions about basic Unity3D operations I recommend consulting Unity3D's documentation or tutorials.

As far as Voxe(lmetric) is concerned, colliders are currently generated for closest chunks around the camera. Requests for collider are controlled via chunk's NeedsCollider variable. Navigate to ProcessChunk method of you chunk loader (LoadChunksSimple by default) and modify it as needed.
