### ISSUE TITLE
Where are the caves?

### ISSUE THREAD

**Issue by odivalq** [richardbiely/Voxelmetric#61]
Are the caves biome active by default? Because no matter how far I travel ingame I can never see any cave. Should I tweak some setting to have caves on the world gen? #

**Comment by richardbiely** [comment]
No such thing as "caves" is hardcoded in the framework just like there is no support for biomes at the moment.
However, you can create you own terrain extension layers that alter the looks of the game world. The easiest way to do so is by editing CavesLayer.cs in Examples folder (or create your own extension layer)
