### ISSUE TITLE
Issue with Voxelmetric.SetBlock()

### ISSUE THREAD

**Issue by aesliva** [richardbiely/Voxelmetric#63]
Hi,

Just wanted to report that structures are no longer generating, and blocks are not being set using Voxelmetric.SetBlock(). It seems to have been caused after some of the functionality from ChunkBlocks was moved to Chunk, though I may be wrong.

-Thanks! And, I just wanted to add that this is an impressive project you're working on, keep up the great work! :)

**Comment by richardbiely** [comment]
Are you sure? I didn't have time to look into the code but I can see trees and magica vox models are still generated.

**Comment by aesliva** [comment]
Ah, the part about structures not generating was on my end, I've fixed it, I apologize. Regarding Voxelmetric.SetBlock, I'll continue looking into that one. I can't think of any changes I've personally made that would cause this, but if I find a fix I'll let you know.

**Comment by richardbiely** [comment]
I've just verified that set VoxelMetric.SetBlock / world.blocks.Modify work properly. It's easy to verify because this is the method the example uses to dig / place new blocks.
I'm marking the ticket invalid but letting it open for the time being until you figure out what's wrong just in case.

**Comment by aesliva** [comment]
After adding the changes from dabb5167929c9a83c76019835328071377493f57 the issue was fixed. Was just a little behind. :T

 My guess is that under Chunk.UpdateBlocks(), the check for AreNeighborsSynchronizing() was returning true?

**Comment by richardbiely** [comment]
Sometimes I get creative but then have to sleep or postpone the final touches for later and it takes a day or two for stability to catch up ;)
It's not too important discussing unfinished/broken code as long as it's been fixed already ;)
