### ISSUE TITLE
Water & Biome Support?

### ISSUE THREAD

**Issue by Logabe** [richardbiely/Voxelmetric#70]
I was wondering if you were going to add support for water & biomes?

**Comment by richardbiely** [comment]
I am, but most likely not in this project but its successor which is in the works.

**Comment by aesliva** [comment]
Hate to reply to a closed issue, but was just curious about the successor to this project. Sounds very interesting! Would like to know more information if any is available, and would it be open source as well?

**Comment by richardbiely** [comment]
Opensource :) And better. I'm pretty busy so the progresses is slow, though

**Comment by aesliva** [comment]
Very exciting! Would definitely keep an eye on it once available.
