### ISSUE TITLE
Pathfinding / Navigation

### ISSUE THREAD

**Issue by Tsilliev** [richardbiely/Voxelmetric#72]
Hello,

Let me say thank you for developing this project.
I have a question regarding the navigation, I found a comment online saying that there is the pathfinder script in the project.
I also went into the VoxelmetricExample script that is attached to the "Game" gameobject from the scene and I saw the button shortcuts using the pathfinder function, but still not sure how its supposed to move anything? 
I understand that "I" is to indicate the start, "P" the end point and "O" to execute the function.
But there is no navmesh, that the char can move on?

```
// Pathfinding
                    if (Input.GetKeyDown(KeyCode.I))
                    {
                        if (hit.block.Type!=BlockProvider.AirType)
                        {
                            bool adjacent = block.Type!=BlockProvider.AirType;
                            pfStart = adjacent ? hit.adjacentPos : hit.vector3Int;
                        }
                    }

                    if (Input.GetKeyDown(KeyCode.O))
                    {
                        if (hit.block.Type!=BlockProvider.AirType)
                        {
                            bool adjacent = block.Type!=BlockProvider.AirType;
                            pfStop = adjacent ? hit.adjacentPos : hit.vector3Int;
                        }
                    }

                    if (Input.GetKeyDown(KeyCode.P))
                    {
                        pf = new PathFinder(pfStart, pfStop, world, 0);
                    }
```

**Comment by richardbiely** [comment]
Hi,
reading the code you pasted, you use I to mark the start, O to mark the end and P to perform the search. P creates a PathFinder object filled with positions you need to visit in order to get from I to O. It's up to you to implement the transition part for it's very game specific.
